name: checador_tique
description: "Checador de Asistencia de Tique"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  geolocator: ^14.0.2
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  connectivity_plus: ^5.0.2
  path: ^1.9.0
  intl: ^0.18.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
